// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CheckPostInListTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void checkPostInList() {
    driver.get("https://ruswizard.site/test");
    vars.put("linkText", driver.findElement(By.cssSelector(".widget_meta li:nth-child(1)")).getText());
    if ((Boolean) js.executeScript("return (arguments[0] == \'Регистрация\')", vars.get("linkText"))) {
      driver.findElement(By.linkText("Войти")).click();
      driver.findElement(By.id("user_login")).click();
      driver.findElement(By.id("user_login")).sendKeys("Kotek_Myau");
      driver.findElement(By.id("user_pass")).click();
      driver.findElement(By.id("user_pass")).sendKeys("wPJ3Kdey(py!m9iQ");
      driver.findElement(By.id("wp-submit")).click();
    }
    driver.findElement(By.cssSelector("#wp-admin-bar-new-content .ab-label")).click();
    driver.findElement(By.id("post-title-0")).click();
    driver.findElement(By.id("post-title-0")).sendKeys("TestCheckPost");
    vars.put("id", js.executeScript("const alink = document.getElementsByClassName(\"components-external-link edit-post-post-link__link\")[0].text; return (new RegExp(\"p=(\\\\\\d+)\")).exec(alink)[1];"));
    driver.findElement(By.cssSelector(".block-editor-writing-flow__click-redirect")).click();
    driver.findElement(By.cssSelector(".editor-post-publish-panel__toggle")).click();
    driver.findElement(By.cssSelector(".editor-post-publish-button")).click();
    driver.findElement(By.cssSelector(".edit-post-fullscreen-mode-close path")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, 50);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector(".mine")));
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".post-vars.get("id").toString()"));
      assert(elements.size() > 0);
    }
  }
}
